import { type Coach, type Player, type TeamName } from './TeamRoasterData'

export interface TeamStatsData {
    TeamID: number
    TeamName: TeamName
    GameCount: number
    Points: number
    Shot1: number
    Goal1: number
    Shot2: number
    Goal2: number
    Shot3: number
    Goal3: number
    Shot23: number
    Goal23: number
    Shots1: string
    Shots2: string
    Shots3: string
    Shot1Percent: string
    Shot2Percent: string
    Shot3Percent: string
    AvgShots1: string
    AvgShots2: string
    AvgShots3: string
    Shots23: string
    Shot23Percent: string
    AvgShots23: string
    Assist: number
    Blocks: number
    DefRebound: number
    OffRebound: number
    Rebound: number
    Steal: number
    Turnover: number
    TeamDefRebound: number
    TeamOffRebound: number
    TeamRebound: number
    TeamSteal: number
    TeamTurnover: number
    KPI: number
    AvgPoints: string
    AvgAssist: string
    AvgBlocks: string
    AvgDefRebound: string
    AvgOffRebound: string
    AvgRebound: string
    AvgSteal: string
    AvgTurnover: string
    AvgFoul: string
    AvgOpponentFoul: string
    AvgPlusMinus: string
    AvgTeamDefRebound: string
    AvgTeamOffRebound: string
    AvgTeamRebound: string
    AvgTeamSteal: string
    AvgTeamTurnover: string
    Foul: number
    OpponentFoul: number
    Seconds: number
    PlayedTime: string
    AvgPlayedTime: string
    PlusMinus: number
    Players: Player[]
    Coaches: Coach[]
}
