export interface TeamGameData {
    GameID: number
    IsToday: boolean
    DaysFromToday: number
    GameNumber: string
    GameDateInt: number
    GameDate: string
    HasTime: boolean
    GameTime: string
    GameTimeMsk: string
    GameLocalDate: string
    GameDateTime: string
    GameDateTimeMoscow: string
    DisplayDateTimeLocal: string
    DisplayDateTimeMsk: string
    DisplayDateTimeLocalEn: string
    DisplayDateTimeMskEn: string
    GameStatus: number
    TeamAid: number
    TeamBid: number
    ShortTeamNameAru: string
    ShortTeamNameBru: string
    TeamNameAru: string
    TeamNameBru: string
    CompTeamNameAru: string
    CompTeamNameBru: string
    RegionTeamNameAru: string
    RegionTeamNameBru: string
    ShortTeamNameAen: string
    ShortTeamNameBen: string
    TeamNameAen: string
    TeamNameBen: string
    CompTeamNameAen: string
    CompTeamNameBen: string
    RegionTeamNameAen: string
    RegionTeamNameBen: string
    ScoreA: number
    ScoreB: number
    Periods: number
    TeamLogoA: string
    TeamLogoB: string
    HasVideo: boolean
    LiveID: string
    TvRu: string
    TvEn: string
    VideoID: string
    RegionRu: string
    RegionEn: string
    RegionId: number
    ArenaEn: string
    ArenaRu: string
    ArenaId: number
    GameAttendance: number
    CompNameRu: string
    CompNameEn: string
    LeagueNameRu: string
    LeagueNameEn: string
    LeagueShortNameRu: string
    LeagueShortNameEn: string
    Gender: number
}
